spring:
  datasource:
    url: jdbc:mysql://umc-5th-db.c6hcuy2mklpv.ap-northeast-2.rds.amazonaws.com:3306/study
    username: root
    password: root1234!
    driver-class-name: com.mysql.cj.jdbc.Driver
  sql:
    init:
      mode: never
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        show_sql: true
        format_sql: true
        use_sql_comments: true
        hbm2ddl:
#          auto: create  # 기존 테이블을 없애고 새로 생성된다
          auto: update   # 바뀐 부분에 대해서만 적용
        default_batch_fetch_size: 1000